### ISSUE TITLE
[AB#7] Add support for EXISTS([]) should always return true, regardless of input claims.

### ISSUE THREAD

**Issue by aidan-g** [Lokulus/ClaimsTransformation#12]
The expression EXISTS([]) returns true if any claims are present, otherwise false. 
This is a breaking change from the previous version of this library where EXISTS([]) always returns true.

In order to reduce risk from the upgrade we should have a compatibility flag which preserves the old behaviour.

**Comment by ghost** [comment]
Implemented since aac6036fb48bcf18bca43fe94a53bcdad7e14144.
